### ISSUE TITLE
github notes

### ISSUE THREAD

**Issue by cecileane** [morrowcj/Stat679-Notes#1]
Hi Clay, you just need to go to your github repository of interest, click on the "issues" tab, then click "new issue": same thing you did, but from this repository instead of that one:
https://github.com/UWMadison-computingtools-2018/hw1-morrowcj/issues/4
Github will automatically add a link from the other issue to here, because I put a link to the other issue.

Very nice notes btw!

**Comment by morrowcj** [comment]
It wasn't letting me tag you guys in it. I'll try again though.



- Clay Morrow


-------- Original message --------

**Comment by cecileane** [comment]
oh, I see. github didn't help you tag us, because we are not collaborators on this repository. But you can still tag us if you know our github user names. Click on "preview" to see if the github names appear in bold. If so, github recognized the github names. If not, github did recognize the name, so there might be a typo.
